-- 11 Math Library --

print(-5)
print(math.abs(-5)) -- Absolute value

print(math.ceil(4.2)) -- Round up
math.floor(4.2) -- Round down
math.round(4.2) -- Round to nearest integer

print(math.max(1, 2, 3, 4, 5)) -- Returns the largest number
print(math.min(1, 2, 3, 4, 5)) -- Returns the smallest number

math.randomseed(1234) -- Set the seed for the random number generator
print(math.random()) -- Returns a random number between 0 and 1
print(math.random(1, 100)) -- Returns a random number between 1 and 100
